version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  cooldown:
    semver-major-days: 14
    semver-minor-days: 7
    semver-patch-days: 2
  ignore:
    - dependency-name: "govuk-components" # TODO: CRM457-2751: Need to ignore until we can upgrade
  groups:
    bundler:
      patterns:
        - "*"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  ignore:
    - dependency-name: "puppeteer"
    - dependency-name: "puppeteer-core"
    - dependency-name: "govuk-frontend" # Need to ignore for now until we're ready for the banner deprecation
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  cooldown:
    semver-major-days: 14
    semver-minor-days: 7
    semver-patch-days: 2
  groups:
    npm-babel:
      patterns:
        - "*"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    github-actions:
      patterns:
        - "*"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
    timezone: Europe/London
  groups:
    docker:
      patterns:
        - "*"
  open-pull-requests-limit: 10
