inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'vendor/**/*'
    - 'gems/laa_multi_step_forms/spec/dummy/**/*'

####################################
## Customization for this project ##
####################################

# Disabled cops
###############

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

# TODO: revisit this once app operational
RSpec/PendingWithoutReason:
  Enabled: false

# Rspec cops
############

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# fully disabled as could not exclude spec/steps/ directory
RSpec/FilePath:
  Enabled: false

# Enabled but tweaked cops
##########################

Metrics/ClassLength:
  Exclude:
    - app/services/decisions/**/*
# To be tweaked until we find the right balance
Metrics/MethodLength:
  Max: 15
  Exclude:
    - app/presenters/nsm/check_answers/**/*
    - spec/system/support/prior_authority/step_helpers.rb

# To be tweaked until we find the right balance
Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Metrics/ParameterLists:
  Max: 7

Layout/LineLength:
  Exclude:
    - spec/decisions/**/*

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/BlockForwarding
Naming/BlockForwarding:
  EnforcedStyle: explicit

# https://rubydoc.info/gems/rubocop/0.82.0/RuboCop/Cop/Naming/MethodParameterName
Naming/MethodParameterName:
  AllowedNames:
    - as

# Rubocop mistakenly consider `#values` method as being called on a Hash
Style/HashEachMethods:
  Exclude:
    - app/value_objects/value_object.rb
    - app/forms/nsm/steps/**/*
    - spec/forms/nsm/steps/case_disposal_form_spec.rb
    - spec/factories/*

Performance/InefficientHashSearch:
  Exclude:
    - app/presenters/nsm/cost_summary/disbursements.rb

Naming/PredicateName:
  AllowedMethods:
    - has_nino
    - has_codefendants
    - has_one_association

# TODO: adjust these values towards the rubocop defaults
RSpec/MultipleMemoizedHelpers:
  Max: 20
  Exclude:
    - spec/forms/nsm/steps/claim_details_form_spec.rb
    - spec/forms/nsm/steps/work_items_add_form_spec.rb
    - spec/presenters/nsm/cost_summary/report_spec.rb
    - spec/presenters/nsm/check_answers/your_details_card_spec.rb

RSpec/MultipleExpectations:
  Max: 7
  Exclude:
    - spec/presenters/nsm/summary/sections/*

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - spec/steps/**/integration_spec.rb
    - spec/presenters/nsm/check_answers/**/*
    - spec/services/submit_to_app_store/nsm_payload_builder_spec.rb
    - spec/system/**/*

Lint/MissingSuper:
  Exclude:
    - 'app/components/*'
    - 'app/presenters/nsm/cost_summary/*'
    - 'app/presenters/nsm/check_answers/*'

Rails/RedundantActiveRecordAllMethod:
  Exclude:
    - 'spec/models/matter_type_spec.rb'
    - 'spec/models/outcome_code_spec.rb'
    - 'app/presenters/**/*'

# Causing false positives when implemented in methods
Rails/ActionControllerFlashBeforeRender:
  Enabled: false
