{{ if not .Values.branch }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clamav
spec:
  replicas: {{ .Values.replicaCount.clamav }}
  revisionHistoryLimit: 2
  minReadySeconds: 15
  serviceName: clamav
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: submit-crime-forms-clamav
  template:
    metadata:
      labels:
        app: submit-crime-forms-clamav
        tier: backend
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 10000
        runAsGroup: 10000
        runAsNonRoot: true
      containers:
      - name: clamav
        image: clamav/clamav-debian:stable
        imagePullPolicy: Always
        command: ["/init-unprivileged"]
        securityContext:
          {{- include "laa-submit-crime-forms.defaultSecurityContext" . | nindent 12 }}
        ports:
          - containerPort: 3310
            protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: clamav-signatures
          - mountPath: /var/log/clamav
            name: clamav-log
          - mountPath: /etc/clamav/freshclam.conf
            name: freshclam-config
            subPath: freshclam.conf
            readOnly: true
          - mountPath: /tmp
            name: tmp
        resources:
          requests:
            cpu: 25m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 3Gi
        readinessProbe:
          tcpSocket:
            port: 3310
          initialDelaySeconds: 60
          periodSeconds: 60
        livenessProbe:
          tcpSocket:
            port: 3310
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
        - name: clamav-log
          emptyDir: {}
        - name: freshclam-config
          configMap:
            name: configmap-clamav-staging
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: clamav-signatures
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-configmap-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
data:
  freshclam.conf: |
    PrivateMirror https://laa-clamav-mirror-production.apps.live.cloud-platform.service.justice.gov.uk
    UpdateLogFile /var/log/clamav/freshclam.log
    NotifyClamd /etc/clamav/clamd.conf
{{ end }}
