apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-submit-crime-forms.fullname" . }}
  labels:
    {{- include "laa-submit-crime-forms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.app }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      {{- include "laa-submit-crime-forms.selectorLabels" . | nindent 6 }}
      app: {{ include "laa-submit-crime-forms.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laa-submit-crime-forms.selectorLabels" . | nindent 8 }}
        app: {{ include "laa-submit-crime-forms.fullname" . }}
        metrics-target: {{ include "laa-submit-crime-forms.fullname" . }}-metrics-target
    spec:
      serviceAccountName: {{ .Values.service_account.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- include "laa-submit-crime-forms.defaultSecurityContext" . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
            - containerPort: 9394
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.app_resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 30"] # Workaround for occasional lost requests - see https://github.com/puma/puma/blob/master/docs/kubernetes.md#running-puma-in-kubernetes
          env:
          {{ if .Values.redis.enabled }}
            - name: REDIS_PROTOCOL
              value: "redis"
            - name: REDIS_HOST
              value: {{ template "helm_deploy.redisUatHost" . }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password }}
          {{ else }}
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: crm-elasticache
                  key: primary_endpoint_address
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crm-elasticache
                  key: auth_token
          {{ end }}
          {{ if .Values.postgresql.enabled }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.postgresPassword }}
            - name: POSTGRES_HOST
              value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: DATABASE_SSLMODE
              value: 'prefer'
          {{ else }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: url
          {{ end }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key_base
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn
                  key: url
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket-output
                  key: bucket_name
            - name: GOVUK_NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: notify-key
                  key: notify_key
            - name: AWS_REGION
              value: 'eu-west-2'
            - name: RACK_ENV
              value: 'production'
            - name: RAILS_ENV
              value: 'production'
            - name: RAILS_LOG_TO_STDOUT
              value: enabled
            - name: APP_STORE_URL
              value: {{ .Values.variables.appStore }}
            - name: ENV
              value: {{ .Values.variables.environment}}
            - name: ENTRA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: entra-client-id
            - name: ENTRA_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: entra-tenant-id
            - name: ENTRA_CERTIFICATE_DATA
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: entra-certificate-data
            - name: LAA_PORTAL_SP_CERT
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: tls.crt
            - name: LAA_PORTAL_SP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: tls.key
            - name: LAA_PORTAL_IDP_METADATA_FILE
              value: {{ .Values.variables.portalIDPMetadataFile }}
            - name: SP_ENTITY_ID
              value: {{ .Values.variables.spEntityId }}
            - name: NSM_MAX_UPLOAD_SIZE_BYTES
              value: {{ mul .Values.variables.nsmMaxFileUploadBytes 1 | quote }}
            - name: PA_MAX_UPLOAD_SIZE_BYTES
              value: {{ mul .Values.variables.paMaxFileUploadBytes 1 | quote }}
            - name: ANALYTICS_TRACKING_ID
              valueFrom:
                secretKeyRef:
                  name: google-analytics
                  key: tracking_key
            - name: APP_STORE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: tenant_id
            - name: APP_STORE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: app_client_id
            - name: PROVIDER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: provider_client_id
            - name: PROVIDER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: provider_client_secret
            - name: SIDEKIQ_WEB_UI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sidekiq-auth
                  key: username
            - name: SIDEKIQ_WEB_UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sidekiq-auth
                  key: password
            - name: CLAMBY_ENABLED
              value: 'true'
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: EOL_URL
              value: {{ .Values.variables.eolUrl }}
            - name: HOSTS
              value: {{ range $index, $hostObject := .Values.ingress.hosts }}{{ if ne $index 0 }},{{ end }}{{ $hostObject.host }}{{ end }}
            - name: INTERNAL_HOST_NAME
              value: {{ template "helm_deploy.internalHostName" . }}
            - name: ALLOW_INDEXING
              value: '{{ .Values.variables.allowIndexing }}'
            - name: SEND_EMAILS
              value: 'true'
            - name: ENABLE_PROMETHEUS_EXPORTER
              value: 'true'
            - name: MAINTENANCE_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "laa-submit-crime-forms.fullname" . }}
                  key: MAINTENANCE_MODE
            - name: PROVIDER_API_HOST
              value: '{{ .Values.variables.providerApiHost }}'
            - name: PROVIDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: provider_api_key
            - name: CLAMD_CONF_FILENAME
              value: clamd.cloud-platform.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
