{
 "title": "LAA non-standard crime claims / Provider sidekiq metrics",
 "description": "Visual Sidekiq Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of enqueued jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ruby_sidekiq_stats_enqueued{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of failed jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ruby_sidekiq_stats_failed{namespace=\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Failed growth",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(ruby_sidekiq_stats_failed[1m])"
    }
   ]
  },
  {
   "title": "Retry jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ruby_sidekiq_stats_retry_size" }
   ]
  },
  {
   "title": "Dead jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ruby_sidekiq_stats_dead_size" }
   ]
  },
  {
   "title": "Enqueued jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ruby_sidekiq_stats_enqueued" }
   ]
  },
  {
   "title": "Busy workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ruby_sidekiq_process_busy" }
   ]
  },
  {
   "title": "Scheduled jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_scheduled_size"
    }
   ]
  },
  {
   "title": "Jobs processed every second",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ruby_sidekiq_jobs_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "All jobs"
    },
    {
     "expr": "sum(rate(ruby_sidekiq_failed_jobs_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Failed jobs"
    }
   ]
  },
  {
   "title": "Number of jobs actively being processed",
   "type": "graph",
   "description": "Number of jobs waiting in queues to be executed",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_sidekiq_stats_workers_size{namespace=\"$namespace\"})",
     "legendFormat": "Jobs being processed"
    }
   ]
  }
 ]
}