source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in laa_multi_step_forms.gemspec.
gemspec

gem 'sqlite3'

gem 'sprockets-rails'

group :development, :test do
  gem 'debug'
  gem 'pry'
end

group :test do
  gem 'simplecov'
  gem 'simplecov-lcov'
  gem 'simplecov-rcov'
end
