source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in laa_multi_step_forms.gemspec.
gemspec

gem 'hmcts_common_platform', github: 'ministryofjustice/hmcts_common_platform', tag: 'v0.2.0'

gem 'sqlite3'

gem 'sprockets-rails'

group :development, :test do
  gem 'debug'
  gem 'pry'
  gem 'rspec_junit_formatter', require: false
  gem 'rspec-rails'
end

group :test do
  gem 'pg', '~> 1.5'
  gem 'rails-controller-testing'
  gem 'rspec-html-matchers'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'simplecov'
  gem 'simplecov-rcov'
end
