source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in laa_multi_step_forms.gemspec.
gemspec

gem 'sqlite3'

group :development, :test do
  gem 'debug'
  gem 'pry'
  gem 'rspec_junit_formatter', require: false
  gem 'rspec-rails', '>= 6.1.2'
end

group :test do
  gem 'pg', '~> 1.5'
  gem 'rails-controller-testing'
  gem 'rspec-html-matchers'
  gem 'rubocop', '>= 1.50.0', require: false
  gem 'rubocop-performance', '>= 1.17.0', require: false
  gem 'rubocop-rails', '>= 2.19.0', require: false
  gem 'rubocop-rspec', '>= 2.20.0', require: false
  gem 'simplecov'
  gem 'simplecov-rcov'
end
