# rubocop:disable all
MainOffence = Struct.new(:type, :description) do
  def self.all
    @all ||= [
      new('Offences against the person', 'Assault (common)'),
      new('Offences against the person', 'Battery (common)'),
      new('Offences against the person', 'Assault occasioning actual bodily harm'),
      new('Offences against the person', 'Wounding or inflicting grievous bodily harm'),
      new('Offences against the person', 'Wounding or causing grievous bodily harm with intent'),
      new('Offences against the person', 'Making threats to kill'),
      new('Offences against the person', 'Racially aggravated assaults'),
      new('Offences against the person', 'Assault on constable in execution of duty'),
      new('Offences against the person', 'Resisting or wilfully obstructing constable'),
      new('Offences against the person', 'Assault with intention to resist arrest'),
      new('Offences against the person', 'Attempting to choke, suffocate, strangle etc'),
      new('Offences against the person', 'Endangering the safety of railway passengers'),
      new('Offences against the person', 'Causing bodily injury by explosives'),
      new('Offences against the person', 'Using gunpowder to explode, or sending to any person an explosive substance, or throwing corrosive fluid on a person, with intent to grievous bodily harm'),
      new('Offences against the person', 'Placing explosives etc., with intent to do bodily injury to any person'),
      new('Offences against the person', 'Making or having gunpowder etc., with intent to commit or enable any person to commit a felony'),
      new('Offences against the person', 'Causing miscarriage by poison, instrument'),
      new('Offences against the person', 'Supplying instrument etc. to cause miscarriage'),
      new('Offences against the person', 'Concealment of birth'),
      new('Offences against the person', 'Administering chloroform, laudanum etc.'),
      new('Offences against the person', 'Administering poison etc. so as to endanger life'),
      new('Offences against the person', 'Administering poison with intent to injure etc.'),
      new('Offences against the person', 'Circumcision of females'),
      new('Offences against the person', 'Kidnapping (common law)'),
      new('Offences against the person', 'Hostage taking'),
      new('Offences against the person', 'False imprisonment (common law)'),
      new('Offences against the person', 'Torture'),
      new('Homicide and related grave offences', 'Murder (common law)'),
      new('Homicide and related grave offences', 'Manslaughter (common law)'),
      new('Homicide and related grave offences', 'Causing death by dangerous driving'),
      new('Homicide and related grave offences', 'Causing death by careless driving while under the influence of drink or drugs'),
      new('Homicide and related grave offences', 'Aggravated vehicle taking resulting in death'),
      new('Homicide and related grave offences', 'Killing in pursuance of suicide pact'),
      new('Homicide and related grave offences', 'Complicity to suicide'),
      new('Homicide and related grave offences', 'Soliciting to murder'),
      new('Homicide and related grave offences', 'Child destruction'),
      new('Homicide and related grave offences', 'Infanticide'),
      new('Homicide and related grave offences', 'Abortion'),
      new('Homicide and related grave offences', 'Supplying or procuring means for abortion'),
      new('Homicide and related grave offences', 'Concealment of birth'),
      new('Firearms Offences', 'Possession of firearm without certificate'),
      new('Firearms Offences', 'Possession or acquisition of shotgun without certificate'),
      new('Firearms Offences', 'Dealing in firearms'),
      new('Firearms Offences', 'Shortening of shotgun or possession of shortened shotgun'),
      new('Firearms Offences', 'Possession or acquisition of certain prohibited weapons etc.'),
      new('Firearms Offences', 'Possession of firearm with intent to injure / endanger life'),
      new('Firearms Offences', 'Possession of firearm or imitation firearm with intent to cause fear of violence'),
      new('Firearms Offences', 'Use of firearm to resist arrest'),
      new('Firearms Offences', 'Possession of firearm with criminal intent'),
      new('Firearms Offences', 'Carrying loaded firearm in public place'),
      new('Firearms Offences', 'Possession of firearm without certificate'),
      new('Firearms Offences', 'Trespassing with a firearm'),
      new('Firearms Offences', 'Possession of firearms by person convicted of crime'),
      new('Firearms Offences', 'Acquisition by or supply of firearms to person denied them'),
      new('Firearms Offences', 'Failure to comply with certificate when transferring firearm'),
      new('Firearms Offences', 'Shortening of smooth bore gun'),
      new('Prison Offence', 'Permitting an escape (common law)'),
      new('Prison Offence', 'Rescue (common law)'),
      new('Prison Offence', 'Escape (common law)'),
      new('Prison Offence', 'Escaping from lawful custody without force (common law)'),
      new('Prison Offence', 'Breach of prison (common law)'),
      new('Prison Offence', 'Prison mutiny'),
      new('Prison Offence', 'Assaulting prison officer whilst possessing firearm etc.'),
      new('Prison Offence', 'Harbouring escaped prisoners'),
      new('Prison Offence', 'Assisting prisoners to escape Terrorist Offences'),
      new('Prison Offence', 'Offences under the Terrorism Act 2000'),
      new('Prison Offence', 'Offences against international protection of nuclear material'),
      new('Prison Offence', 'Offences under the Northern Ireland'),
      new('Sexual offences and offences against children', 'Offences under the Sexual Offences Act 2003'),
      new('Sexual offences and offences against children', 'Child abduction by connected person'),
      new('Sexual offences and offences against children', 'Child abduction by other person'),
      new('Sexual offences and offences against children', 'Keeping brothel and related offences'),
      new('Sexual offences and offences against children', 'Keeping a disorderly house'),
      new('Sexual offences and offences against children', 'Soliciting'),
      new('Sexual offences and offences against children', 'Taking, having etc. indecent photographs of children'),
      new('Sexual offences and offences against children', 'Sexual intercourse with patients'),
      new('Sexual offences and offences against children', 'Ill treatment of persons of unsound mind'),
      new('Sexual offences and offences against children', 'Bigamy'),
      new('Sexual offences and offences against children', 'Abuse of position of trust'),
      new('Sexual offences and offences against children', 'Abandonment of children under two'),
      new('Sexual offences and offences against children', 'Cruelty to persons under 16'),
      new('Robbery', 'Armed robbery'),
      new('Robbery', 'Assault with weapon with intent to rob'),
      new('Burglary', 'Burglary (domestic)'),
      new('Burglary', 'Going equipped to steal'),
      new('Burglary', 'Burglary (non-domestic)'),
      new('Burglary', 'Aggravated burglary'),
      new('Criminal Damage and Arson', 'Criminal Damage'),
      new('Criminal Damage and Arson', 'Destroying or damaging property with the intention or recklessness as to endanger life'),
      new('Criminal Damage and Arson', 'Aggravated criminal damage'),
      new('Criminal Damage and Arson', 'Threats to destroy or damage property'),
      new('Criminal Damage and Arson', 'Racially aggravated criminal damage'),
      new('Criminal Damage and Arson', 'Possessing anything with intent to destroy or damage property'),
      new('Criminal Damage and Arson', 'Possessing bladed article / instrument'),
      new('Criminal Damage and Arson', 'Prohibition of the carrying of offensive weapons without lawful authority or reasonable excuse'),
      new('Criminal Damage and Arson', 'Arson'),
      new('Criminal Damage and Arson', 'Aggravated arson'),
      new('Criminal Damage and Arson', 'Racially aggravated arson'),
      new('Theft', 'Theft'),
      new('Theft', 'Taking conveyance without authority'),
      new('Theft', 'Taking or riding a pedal cycle without authority'),
      new('Theft', 'Aggravated vehicle taking'),
      new('Theft', 'Handling stolen goods'),
      new('Theft', 'Receiving property by another’s mistake'),
      new('Theft', 'Removal of articles from places open to the public'),
      new('Theft', 'Abstraction of electricity'),
      new('Theft', 'Making off without payment'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraud (common law)'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Copying a false instrument'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Using a false statement'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Using a copy of a false instrument'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Custody or control of false instruments etc.'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Offences relating to money orders, share certificates, passports etc, etc.'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Counterfeiting notes and coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Passing, etc. counterfeiting notes and coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Offences involving the custody/control of counterfeit notes and coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Making, custody or control of counterfeiting materials etc.'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Illegal importation: Counterfeit notes or coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Offences involving the making/custody/control of counterfeiting materials and implements'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Reproducing British currency'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Offences in making, etc., imitation of British coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Prohibition of importation of counterfeit note and coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Prohibition of exportation of counterfeit notes and coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Destruction of registers of births etc.'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Making false entries in copies of registers sent to register'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent evasion: counterfeit notes or coins'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Obtaining services by deception'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Evasion of liability by deception'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Obtaining property by deception'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Obtaining a money transfer by deception'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Obtaining pecuniary advantage by deception'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'False accounting'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Liability of company officers for offences of deception committed by the company'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'False statements by company directors'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Suppression, etc. of documents'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Procuring execution of a valuable security by deception'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Advertising rewards for return of goods stolen or lost'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Dishonestly retaining a wrongful credit'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent use of telecommunication system'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Possession or supply of anything for fraudulent purpose in connection with use of telecommunication system'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Offences under the Companies Act 1985'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Insider dealing'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'False declarations of insolvency in voluntary liquidations'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Concealment of property and failure to account for losses'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Concealment or falsification of books and papers'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'False statements'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent disposal of property'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Absconding with property'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent dealing with property obtained on credit'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Undischarged bankrupt concerned in a company'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Failure to keep proper business accounts'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Misleading statements and practices'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent inducement to make a deposit'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Counterfeiting customs documents'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Offences in relation to dies or stamps'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Counterfeiting of dies or marks'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent application of trademark'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'False application or use of trademarks'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery of driving documents'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery and misuse of driving documents'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery etc. of licenses and other documents'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Mishandling or falsifying parking documents'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery, Alteration etc. of documents etc.'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'False records or entries relating to driver’s hours'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery, alteration, fraud of licences etc.'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery, alteration etc. of licenses, marks, trade plates etc'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Forgery of documents etc.: Motor vehicles (EC Type approval)and motor cycles etc. (EC Type approval)'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Fraudulent evasion of agricultural levy'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Evasion of duty'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'Trade description offences (9 offences)'),
      new('Fraud, Forgery and other Offences of Dishonesty', 'VAT offences'),
      new('Public order offences', 'Breach of any order made by a court'),
      new('Public order offences', 'Causing explosion likely to endanger life or property'),
      new('Public order offences', 'Attempt to cause explosion, making or keeping explosive etc.'),
      new('Public order offences', 'Making or possession of explosive under suspicious circumstances'),
      new('Public order offences', 'Bomb Hoaxes'),
      new('Public order offences', 'Contamination of goods with intent'),
      new('Public order offences', 'Placing wood etc. on railway'),
      new('Public order offences', 'Exhibiting false signals etc.'),
      new('Public order offences', 'Perjuries (7 offences)'),
      new('Public order offences', 'Offences akin to perjury: False testimony of unsworn child witnesses in criminal proceedings'),
      new('Public order offences', 'Perverting the course of public justice (common law)'),
      new('Public order offences', 'Public nuisance (common law)'),
      new('Public order offences', 'Contempt of court (common law)'),
      new('Public order offences', 'Blackmail'),
      new('Public order offences', 'Corrupt transactions with agents'),
      new('Public order offences', 'Corruption (common law)'),
      new('Public order offences', 'Corruption in public office'),
      new('Public order offences', 'Embracery'),
      new('Public order offences', 'Fabrication of evidence with intent to mislead a tribunal (common law)'),
      new('Public order offences', 'Personation of jurors (common law)'),
      new('Public order offences', 'Concealing an arrestable offence'),
      new('Public order offences', 'Assisting offenders'),
      new('Public order offences', 'False evidence before European Court'),
      new('Public order offences', 'Intimidating a witness, juror etc.'),
      new('Public order offences', 'Harming, threatening to harm a witness, juror etc.'),
      new('Public order offences', 'Ticket touts'),
      new('Public order offences', 'Prejudicing a drug trafficking investigation'),
      new('Public order offences', 'Giving false statements to procure cremation'),
      new('Public order offences', 'False statement tendered under section 9 of the Criminal Justice Act 1967'),
      new('Public order offences', 'False statement tendered under section 102 of the Magistrates’ Courts Act 1980'),
      new('Public order offences', 'Making a false statement to obtain or resist interim possession order'),
      new('Public order offences', 'Making false statement to authorised officer'),
      new('Public order offences', 'Riot'),
      new('Public order offences', 'Violent disorder'),
      new('Public order offences', 'Affray'),
      new('Public order offences', 'Fear or provocation of violence'),
      new('Public order offences', 'Intentional harassment, alarm, or distress'),
      new('Public order offences', 'Harassment, alarm or distress'),
      new('Public order offences', 'Harassment of debtors'),
      new('Public order offences', 'Offence of harassment'),
      new('Public order offences', 'Putting people in fear of violence'),
      new('Public order offences', 'Breach of restraining order/injunction'),
      new('Public order offences', 'Racially aggravated public order offences'),
      new('Public order offences', 'Racially aggravated harassment etc.'),
      new('Public order offences', 'Using words or behaviour or displaying written material stirring up racial hatred'),
      new('Public order offences', 'Publishing or distributing written material stirring up racial hatred'),
      new('Public order offences', 'Public performance of play stirring up racial hatred'),
      new('Public order offences', 'Distributing, showing or playing a recording stirring up racial hatred'),
      new('Public order offences', 'Broadcasting programme stirring up racial hatred'),
      new('Public order offences', 'Possession of written material or recording stirring up racial hatred'),
      new('Public order offences', 'Possession of offensive weapon'),
      new('Public order offences', 'Possession of bladed article'),
      new('Public order offences', 'Criminal libel (common law)'),
      new('Public order offences', 'Blasphemy and blasphemous libel (common law)'),
      new('Public order offences', 'Sedition'),
      new('Public order offences', 'Indecent display'),
      new('Public order offences', 'Presentation of obscene performance'),
      new('Public order offences', 'Obstructing railway or carriage on railway'),
      new('Public order offences', 'Obscene articles intended for publication for gain'),
      new('Public order offences', 'Offences of publication of obscene matter'),
      new('Public order offences', 'Agreeing to indemnify sureties'),
      new('Public order offences', 'Absconding by person released on bail'),
      new('Public order offences', 'Personating for purposes of bail etc.'),
      new('Public order offences', 'Sending prohibited articles by post'),
      new('Public order offences', 'Impersonating Customs officer'),
      new('Public order offences', 'Obstructing Customs officer'),
      new('Public order offences', 'Penalty on keepers of refreshment houses permitting drunkenness, disorderly conduct, or gaming, etc., therein'),
      new('Public order offences', 'Penalty on persons found drunk'),
      new('Public order offences', 'Drunkenness in a public place'),
      new('Public order offences', 'Drunk in a late night refreshment house'),
      new('Public order offences', 'Drunk while in charge of a child'),
      new('Public order offences', 'Drunk on an aircraft'),
      new('Public order offences', 'Intimidation or annoyance by violence or otherwise'),
      new('Public order offences', 'Offences affecting security'),
      new('Public order offences', 'Offences under the Official Secrets Act 1911, 1920 and 1989'),
      new('Public order offences', 'Unlawful interception of communications by public and private systems'),
      new('Public order offences', 'Disclosure of telecommunication messages'),
      new('Public order offences', 'Incitement to disaffection'),
      new('Drug Offences', 'Restriction of importation and exportation of controlled drugs'),
      new('Drug Offences', 'Producing or supplying a Class A, B or C drug'),
      new('Drug Offences', 'Possession of controlled drugs'),
      new('Drug Offences', 'Possession of a Class A, B or C drug with intent to supply'),
      new('Drug Offences', 'Cultivation of cannabis plant'),
      new('Drug Offences', 'Occupier knowingly permitting drugs offences etc.'),
      new('Drug Offences', 'Activities relating to opium'),
      new('Drug Offences', 'Prohibition of supply etc., of articles for administering or preparing controlled drugs'),
      new('Drug Offences', 'Offences relating to the safe custody of controlled drugs'),
      new('Drug Offences', 'Practitioner contravening drug supply regulations'),
      new('Drug Offences', 'Incitement'),
      new('Drug Offences', 'Assisting in or inducing commission outside United Kingdom of offence punishable under a corresponding law'),
      new('Drug Offences', 'Powers of entry, search and seizure'),
      new('Drug Offences', 'Illegal importation of Class A, B or C drugs'),
      new('Drug Offences', 'Fraudulent evasion of controls on Class A, B or C drugs'),
      new('Drug Offences', 'Failure to disclose knowledge or suspicion of money laundering'),
      new('Drug Offences', 'Tipping-off in relation to money laundering investigations'),
      new('Drug Offences', 'Offences in relation to proceeds of drug trafficking'),
      new('Drug Offences', 'Offences in relation to money laundering investigations'),
      new('Drug Offences', 'Manufacture and supply of scheduled substances'),
      new('Drug Offences', 'Drug Trafficking offences at sea'),
      new('Drug Offences', 'Ships used for illicit traffic'),
      new('Drug Offences', 'Making and preserving records of production and supply of certain scheduled substances'),
      new('Drug Offences', 'Supply of intoxicating substance'),
      new('Driving and motor vehicle Offences (Other)', 'Dangerous driving'),
      new('Driving and motor vehicle Offences (Other)', 'Careless, and inconsiderate driving'),
      new('Driving and motor vehicle Offences (Other)', 'Driving, or being in charge, when under the influence of drink or drugs'),
      new('Driving and motor vehicle Offences (Other)', 'Driving or being in charge of a motor vehicle with excess alcohol'),
      new('Driving and motor vehicle Offences (Other)', 'Breath tests'),
      new('Driving and motor vehicle Offences (Other)', 'Provision of specimens for analysis'),
      new('Driving and motor vehicle Offences (Other)', 'Motor racing on highways'),
      new('Driving and motor vehicle Offences (Other)', 'Leaving vehicle in dangerous position'),
      new('Driving and motor vehicle Offences (Other)', 'Causing danger to road users'),
      new('Driving and motor vehicle Offences (Other)', 'Restriction of carriage of persons on motor cycles'),
      new('Driving and motor vehicle Offences (Other)', 'Failing to stop at school gate'),
      new('Driving and motor vehicle Offences (Other)', 'Failure to comply with indication given by traffic sign'),
      new('Driving and motor vehicle Offences (Other)', 'Directions to pedestrians'),
      new('Driving and motor vehicle Offences (Other)', 'Using vehicles in dangerous condition'),
      new('Driving and motor vehicle Offences (Other)', 'Contravention of construction and use regulations'),
      new('Driving and motor vehicle Offences (Other)', 'Using etc. motor vehicle without test certificate'),
      new('Driving and motor vehicle Offences (Other)', 'Driving otherwise than in accordance with a licence'),
      new('Driving and motor vehicle Offences (Other)', 'Driving after refusal or revocation of licence'),
      new('Driving and motor vehicle Offences (Other)', 'False declaration as to physical fitness'),
      new('Driving and motor vehicle Offences (Other)', 'Failure to notify disability'),
      new('Driving and motor vehicle Offences (Other)', 'Driving with uncorrected defective eyesight'),
      new('Driving and motor vehicle Offences (Other)', 'Driving while disqualified'),
      new('Driving and motor vehicle Offences (Other)', 'Using etc. motor vehicle without insurance'),
      new('Driving and motor vehicle Offences (Other)', 'Failure to produce driving licence, insurance etc'),
      new('Driving and motor vehicle Offences (Other)', 'Failure to give, or giving false, name and address in case of dangerous or careless or inconsiderate driving or cycling'),
      new('Driving and motor vehicle Offences (Other)', 'Pedestrian contravening constable’s direction to stop to give name and address'),
      new('Driving and motor vehicle Offences (Other)', 'Failing to stop and failing to report accident'),
      new('Driving and motor vehicle Offences (Other)', 'Duty of owner of motor vehicle to give information for verifying compliance with requirement of compulsory insurance or security'),
      new('Driving and motor vehicle Offences (Other)', 'Duty to give information as to identity of driver etc., in certain circumstances'),
      new('Driving and motor vehicle Offences (Other)', 'Street playgrounds'),
      new('Driving and motor vehicle Offences (Other)', 'Speeding'),
      new('Driving and motor vehicle Offences (Other)', 'Wanton or furious driving'),
      new('Driving and motor vehicle Offences (Other)', 'Interference with vehicles'),
      new('Driving and motor vehicle Offences (Other)', 'Other road traffic offences (including policing etc.)'),
      new('Other', 'Proceedings for the making of anti-social behaviour orders, sex offender orders etc'),
      new('Other', 'Failing to keep dogs under proper control resulting in injury and other dog offences'),
      new('Other', 'Failing to keep dogs under proper control resulting in injury and other dog offences'),
      new('Other', 'Hijacking of aircraft'),
      new('Other', 'Destroying, damaging or endangering safety of aircraft'),
      new('Other', 'Other acts endangering or likely to endanger safety of aircraft'),
      new('Other', 'Offences in relation to certain dangerous articles'),
      new('Other', 'Endangering safety at aerodromes Hijacking of ships'),
      new('Other', 'Other offences under the Aviation and Maritime Security Act 1990'),
      new('Other', 'Piracy'),
      new('Other', 'Offences under the Football Spectators Act 1989'),
      new('Other', 'Throwing of missiles'),
      new('Other', 'Indecent or racialist chanting'),
      new('Other', 'Going onto the playing area'),
      new('Other', 'Offences in connection with alcohol on coaches and trains'),
      new('Other', 'Offences in connection with alcohol, containers etc., at sports grounds'),
      new('Other', 'Offences of cruelty (Protection of Animals)'),
      new('Other', 'Penalties for abandonment of animals'),
      new('Other', 'Offences (Wild Mammals Protection)'),
      new('Other', 'Raves'),
      new('Other', 'Offences affecting enjoyment of premises'),
      new('Other', 'Unlawful eviction and harassment of occupier'),
      new('Other', 'Use or threat of violence for purpose of securing entry to premises'),
      new('Other', 'Adverse occupation of residential premises'),
      new('Other', 'Trespassing during the currency of an interim possession order'),
      new('Other', 'Interim possession orders: false or misleading statements'),
      new('Other', 'Aggravated trespass'),
      new('Other', 'Failure to leave or re-entry to land after police direction to leave'),
      new('Other', 'Unauthorised campers')
    ]
  end
  # rubocop:enable all

  def name
    description.to_s
  end
end
