QuoteService = Struct.new(:id, :description) do
  # rubocop:disable Metrics/MethodLength
  def self.all
    @all ||= [
      new('SVCACC', 'Accountant'),
      new('SVCANA', 'Anaesthatist'),
      new('SVCARC', 'Architect'),
      new('SVCAB', 'Animal Behaviourist'),
      new('SVCAC', 'A&E Consultant'),
      new('SVCAR', 'Accident Reconstruction'),
      new('SVCBC', 'Back Calculations'),
      new('SVCBE', 'Benefit Expert'),
      new('SVCC', 'Cardiologist'),
      new('SVCCULE', 'Culture expert'),
      new('SVCCOME', 'Computer Experts'),
      new('SVCONE', 'Consultant Engineer'),
      new('SVCCME', 'Cultural Music Expert'),
      new('SVCCP1', 'Child Pshychiatrist'),
      new('SVCCP2', 'Child Psychologist'),
      new('SVCCSA', 'Cell site analysis'),
      new('SVCCT', 'Court transcription'),
      new('SVCDEN', 'Dentist'),
      new('SVCDER', 'Dermatologist'),
      new('SVCDC', 'Disability Consultant'),
      new('SVCDE', 'Drug Expert'),
      new('SVCDG', 'Doctor (GP)'),
      new('SVCDPP', 'DNA (per person)'),
      new('SVCE', 'Engineer'),
      new('SVCEA', 'Enquiry Agent'),
      new('SVCEEMPC', 'Employment Consultant'),
      new('SVCENCC', 'Encro Chat'),
      new('SVCENVE', 'Enviromental expert'),
      new('SVCES', 'ENT Surgeon'),
      new('SVCFINE', 'Fingerprint Experts'),
      new('SVCFIRE', 'Firearm Expert'),
      new('SVCFI', 'Fire Investigation'),
      new('SVCFM', 'Facial Mapping'),
      new('SVCFP', 'Forensic Psychiatrist'),
      new('SVCFS', 'Forensic Scientist'),
      new('SVCGEN', 'Geneticist'),
      new('SVCGYN', 'Gynaecologist'),
      new('SVCGRR', 'GP (Records Report)'),
      new('SVCGS', 'General Surgeon'),
      new('SVCH', 'Haematologist'),
      new('SVCHE', 'Handwriting Expert'),
      new('SVCHT', 'Human Trafficking'),
      new('SVCINPT', 'Interpreters'),
      new('SVCINTM', 'Intermediary'),
      new('SVCISW', 'Independent Social Worker'),
      new('SVCJVG', 'Jewellery valuation'),
      new('SVCJVG', 'Jewellery Valuer / Gemmologist'),
      new('SVCLF', 'Lab Fees'),
      new('SVCLPEE', 'Legal/Prison expert (extradition)'),
      new('SVCLRS', 'Lip-Reader / Signer'),
      new('SVCMET', 'Meteorologist'),
      new('SVCMID', 'Midwife'),
      new('SVCMC', 'Medical Consultant'),
      new('SVCME', 'Mortgage Expert'),
      new('SVCMF', 'Mediators Fees'),
      new('SVCMM', 'Medical Microbiologist'),
      new('SVCMR', 'Medical Report'),
      new('SVCNEO', 'Neonatologist'),
      new('SVCNEUR1', 'Neurologist'),
      new('SVCNEUR2', 'Neuropathologist'),
      new('SVCNEUR3', 'Neuropsychiatrist'),
      new('SVCNEUR4', 'Neuropsychologist'),
      new('SVCNEUR5', 'Neuroradiologist'),
      new('SVCNEUR6', 'Neurosurgeon'),
      new('SVCNRSE', 'Nursing Expert'),
      new('SVCOBST', 'Obstetrician'),
      new('SVCONC', 'Oncologist'),
      new('SVCOPT', 'Opthalmologist'),
      new('SVCOTHER', 'Other'),
      new('SVCOS', 'Orthopaedic Surgeon'),
      new('SVCOT', 'Occupational Therapist'),
      new('SVCPAE', 'Paediatrician'),
      new('SVCPAT', 'Pathologist'),
      new('SVCPHAR', 'Pharmacologist'),
      new('SVCPHO', 'Photographer'),
      new('SVCPHY', 'Physiotherapist'),
      new('SVCPSY', 'Psychologist'),
      new('SVCPC', 'Psychologist - Child'),
      new('SVCPI', 'Private Investigator'),
      new('SVCPIC', 'Psychiatrist (inc Chld)'),
      new('SVCPPS', 'Photocopying per sheet'),
      new('SVCPRPL1', 'A Psychiatric report (Prison Law)'),
      new('SVCPRPL2', 'A Psychological report (Prison Law)'),
      new('SVCPPLAS', 'Plastic Surgeon'),
      new('SVCPROS', 'Process Server'),
      new('SVCRAD', 'Radiologist'),
      new('SVCRHE', 'Rheumatologist'),
      new('SVCRAE', 'Risk Assessment Expert'),
      new('SVCRW', 'report writing'),
      new('SVCSGN', 'Surgeon'),
      new('SVCSURV', 'Surveyor'),
      new('SVCSB', 'Specialist Barristers (Land, Property, Chancery Law)'),
      new('SVCSE', 'Sleep expert'),
      new('SVCSHD', 'Surveyor (housing disrepair)'),
      new('SVCST', 'Speech Therapist'),
      new('SVCTOX', 'Toxicologist'),
      new('SVCTRA', 'Travel'),
      new('SVCTATW', 'Translation and Transcription (word counts)'),
      new('SVCTD', 'Translator (documents)'),
      new('SVCTACE', 'Tachograph Expert'),
      new('SVCTELEE', 'Telecoms Expert'),
      new('SVCTRA', 'Transcripts (recordings)'),
      new('SVCU', 'Urologist'),
      new('SVCV', 'Vet'),
      new('SVCVR', 'Voice Recognition'),
      new('SVCINT042022', 'Intermediary submitted after 1st April 2022'),
    ]
  end
  # rubocop:enable Metrics/MethodLength

  def self.description_by_id(matter_id)
    all.find { |item| item.id == matter_id }.description
  end

  def name
    "#{id} - #{description}"
  end
end
